name: Snyk Code Scan

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*"'
      - 'feature/*'
      - 'issue/*'
    paths-ignore:
      - '.github/workflows/*'
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'development'
      - 'release/v*"'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security:
    name: Snyk Code Scan
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: dafneb/.github/.github/workflows/snyk-code-scan-python.yml@2447bb5e1b5f31b2c534e3590cdc543a93576db2
    secrets: inherit
