name: Snyk Code Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*"'
      - 'feature/*'
      - 'issue/*'
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'development'
      - 'release/v*"'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security:
    name: Snyk Code Scan
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: dafneb/.github/.github/workflows/snyk-code-scan-python.yml@main
    secrets: inherit
